## numpy

处理数值型数据

科学计算的基础库

多用于大型、多维数组（列表）上执行数值运算



#### 创建数组

In [1]:
# 使用numpy生成数组，得到ndarray的类型
import numpy as np
import random

t1 = np.array([1,2,3,])
print(t1)
print(type(t1))

t2 = np.array(range(10))
print(t2)
print(type(t2))

t3 = np.arange(10)
print(t3)
print(type(t2))

t4 = np.arange(4,10,2)
print(t4)
print(type(t4))
print(t4.dtype)

t5 = np.array(range(1,4),dtype=float)
print(t5)
print(t5.dtype)

# bool类型
t6 = np.array([1,1,0,1,0,0],dtype=bool)
print(t6)
print(t6.dtype)

# 调整数据类型
t7 = t6.astype("int8")
print(t7)
print(t7.dtype)

# numpy中的小数
t8 = np.array([random.random() for i in range(10)])
print(t8)
print(t8.dtype)

# 保留两位小数
t9 = np.round(t8,2)
print(t9)
print(t9.dtype)

[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[4 6 8]
<class 'numpy.ndarray'>
int32
[1. 2. 3.]
float64
[ True  True False  True False False]
bool
[1 1 0 1 0 0]
int8
[0.87806798 0.20945655 0.58421324 0.81946087 0.20020619 0.98317188
 0.49973051 0.4884952  0.73055281 0.03556013]
float64
[0.88 0.21 0.58 0.82 0.2  0.98 0.5  0.49 0.73 0.04]
float64


#### 数组的形状

In [2]:
import numpy as np
import random

# 一维数组
t1 = np.arange(12)
print(t1)
print(t1.shape)

# 二维数组
t2 = np.array([[1,2,3],[4,5,6]])
print(t2)
print(t2.shape)

# 三维数组
t3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t3)
print(t3.shape)

# 修改形状
t4 = np.arange(12)
t4 = t4.reshape((3,4))
print(t4)
print(t4.shape)

t5 = np.arange(24).reshape((2,3,4))
print(t5)

# reshape对原数组无影响
t6 = t5.reshape((4,6))
# print(t5)
print(t6)
print(t6.reshape((24,))) # 一维
print(t6.reshape((24,1))) # 二维
print(t6.reshape((1,24))) # 二维
print(t6.reshape((t6.shape[0]*t6.shape[1],))) # 计算总数后一维展开
print(t6.flatten()) # 直接按行展开


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


#### 数组计算

广播原则，如果两个数组的后缘维度（即从末尾开始算起的维度）的轴长相符或其中一方的长度为1，则认为它们是广播兼容的。广播会在缺失和（或）长度为1的维度上进行

即对于一个二维的数组，其可与任意行数或列数与其相等，而另一个值为1的数组进行计算

而三维中
(3,3,3)不能和(3,2)进行计算

(3,3,2)不能和(3,3)进行计算，但可以和(3,2)以及(3,1)进行计算

In [3]:
import numpy as np
import random

#数组和数字进行计算
t1 = np.arange(24).reshape((4,6))
print(t1)
print(t1+2) # 数组全加2
print(t1*2) # 数组全乘2
print(t1/2) # 数组全除2
print(t1/0) # 数组全除0，nan=not a number(专指0/0)，inf=infinite（无限）

# 数组和数组进行计算
t2 = np.arange(100,124).reshape((4,6)) # 两数组形状相同
print(t2)
print(t1+t2) # 对应位置一一相加
print(t1*t2) # 对应位置一一相乘
print(t2/t1) # 对应位置一一相除

t3 = np.arange(0,6) # 一行但列数相同
print(t3)
print(t3+t1) # 对应列所有数均相加
print(t3*t1) # 对应列所有数均相乘
print(t1*t3) # 结果同上
print(t1/t3) # 对应列所有数均相除
print(t3/t1) # t3每个数分别相除对应列上每个数

t4 = np.arange(4).reshape((4,1)) # 一列但行数相同
print(t4)
print(t4+t1) # 对应行所有数均相加
print(t4*t1) # 对应行所有数均相乘
print(t1*t4) # 结果同上
print(t4/t1) # t4每个数分别相除对应行上每个数
print(t1/t4) # 对应行所有数均相除

t5 = np.arange(10)
print(t5)
# print(t5+t1) 行列均不相同时无法计算


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]]
[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]
[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]
[[nan inf inf inf inf inf]
 [inf inf inf inf inf inf]
 [inf inf inf inf inf inf]
 [inf inf inf inf inf inf]]
[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]
[[100 102 104 106 108 110]
 [112 114 116 118 120 122]
 [124 126 128 130 132 134]
 [136 138 140 142 144 146]]
[[   0  101  204  309  416  525]
 [ 636  749  864  981 1100 1221]
 [1344 1469 1596 1725 1856 1989]
 [2124 2261 2400 2541 2684 2829]]
[[         inf 101.          51.          34.33333333  26.
   21.        ]
 [ 17.66666667  15.28571429  13.5         12.11111111  11.
   10.09090909]
 [

C:\Users\admin\AppData\Local\Temp\ipykernel_30712\1298134405.py:10: RuntimeWarning: divide by zero encountered in divide
  print(t1/0) # 数组全除0，nan=not a number(专指0/0)，inf=infinite（无限）
C:\Users\admin\AppData\Local\Temp\ipykernel_30712\1298134405.py:10: RuntimeWarning: invalid value encountered in divide
  print(t1/0) # 数组全除0，nan=not a number(专指0/0)，inf=infinite（无限）
C:\Users\admin\AppData\Local\Temp\ipykernel_30712\1298134405.py:17: RuntimeWarning: divide by zero encountered in divide
  print(t2/t1) # 对应位置一一相除
C:\Users\admin\AppData\Local\Temp\ipykernel_30712\1298134405.py:24: RuntimeWarning: divide by zero encountered in divide
  print(t1/t3) # 对应列所有数均相除
C:\Users\admin\AppData\Local\Temp\ipykernel_30712\1298134405.py:24: RuntimeWarning: invalid value encountered in divide
  print(t1/t3) # 对应列所有数均相除
C:\Users\admin\AppData\Local\Temp\ipykernel_30712\1298134405.py:25: RuntimeWarning: invalid value encountered in divide
  print(t3/t1) # t3每个数分别相除对应列上每个数
C:\Users\admin\AppData\Local\Temp\ipy

#### 轴（axis）

可以理解为方向，用0,1,2,3.....数字表示，对于一维数组，只有0轴，对于二维数组，则有0轴和1轴，三维数组，有0轴，1轴，2轴。

如shape(3,2,3)为三维数组，是3块，每块2行3列，0轴为3，1轴为2，2轴为3

计算二维数组的平均值，必须指定哪个轴

#### numpy读取与处理数据

In [4]:
import numpy as np

cwu_file_path = r"china_water_use\data\values_data.csv"

t1 = np.loadtxt(cwu_file_path, delimiter=",", skiprows=1, usecols=[3,4,5,6], dtype=float) # unpack:转置，默认为False

print(t1)

# 实现转置
# print(t1.transpose())
# print(t1.T)
# print(t1.swapaxes(1,0))

# 取行
print(t1[1]) # 取单行
print(t1[1:]) # 取连续多行
print(t1[[2,8,10]]) # 取不连续多行
print(t1[1,:]) # 取第二行
print(t1[2:,:]) # 取第三行及之后所有
print(t1[[2,8,10],:]) # 取不连续多行

# 取列
print(t1[:,0]) # 取单列
print(t1[:,2:])  # 取连续多列
print(t1[:,[0,2,3]]) # 取不连续多列

# 取行列
print(t1[3,2]) # 一行一列=取某一点,即某个数值
print(t1[2:5,1:4]) # 取第3到第5行，第2到第4列，即交叉点的各元素
print(t1[[0,2],[0,1]]) # 取多个不相邻的点(0,0),(2,1)

# numpy中数值的修改
# t1[2,1] = 0
# print(t1)

# 利用bool数组索引
print(t1<10)
# t1[t1<10] = 1
# print(t1)
print(t1[t1<10])

# 三元运算符
t2 = np.where(t1<=10,100,300) # 小于等于10的部分换成100，大于10的部分换成300,不改变原数组
# print(t1)
print(t2)

# 裁剪
t3 = t1.clip(10,100) # 小于10的部分换成0，大于100的部分换成100，不改变原数组
# print(t1)
print(t3)
t3[2,2] = np.nan #强行复赋值nan，nan为浮点型
print(t3)

[[  1.22992663 127.31562503  59.83483763   8.28971932]
 [  1.27445194 129.9680973   62.35518551   7.81960194]
 [  1.48286667 152.16337994  68.73692252   9.77692318]
 ...
 [  1.0807812  692.88040102 138.49146153  27.91294207]
 [  1.04199855 702.99765803 138.0813854   25.20437515]
 [  1.13957301 677.40811612 130.90477757  20.45208954]]
[  1.27445194 129.9680973   62.35518551   7.81960194]
[[  1.27445194 129.9680973   62.35518551   7.81960194]
 [  1.48286667 152.16337994  68.73692252   9.77692318]
 [  1.5387312  156.78772199  74.00581528  10.51105105]
 ...
 [  1.0807812  692.88040102 138.49146153  27.91294207]
 [  1.04199855 702.99765803 138.0813854   25.20437515]
 [  1.13957301 677.40811612 130.90477757  20.45208954]]
[[  1.48286667 152.16337994  68.73692252   9.77692318]
 [  1.54772697 145.69669589  92.53551843   8.28178137]
 [  1.73595791 163.56236209 106.30565735   9.4848521 ]]
[  1.27445194 129.9680973   62.35518551   7.81960194]
[[  1.48286667 152.16337994  68.73692252   9.77692318]